
name: DevOps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "terraform/**"
      - ".github/workflows/**"

concurrency:
  group: devops-pipeline
  cancel-in-progress: true

env:
  ACR_NAME: devopsghacr98421
  ACR_LOGIN_SERVER: devopsghacr98421.azurecr.io
  IMAGE_NAME: devops-node-app
  RESOURCE_GROUP: devops-gha-rg
  CONTAINER_APP_DEV: devops-app-dev
  CONTAINER_APP_PROD: devops-app-prod

jobs:

  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test


  security-scan:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: HIGH,CRITICAL


  build-push-image:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name $ACR_NAME

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build Cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} ./app

      - name: Push Docker image
        run: docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}


  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-push-image

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Wait for Container App provisioning
        run: |
          while true; do
            STATUS=$(az containerapp show \
            --name $CONTAINER_APP_DEV \
            --resource-group $RESOURCE_GROUP \
            --query properties.provisioningState \
            -o tsv)

            echo "Current state: $STATUS"

            if [ "$STATUS" = "Succeeded" ] || [ "$STATUS" = "Provisioned" ]; then
              break
            fi

            sleep 10
          done

      - name: Deploy DEV container
        run: |
          az containerapp update \
          --name $CONTAINER_APP_DEV \
          --resource-group $RESOURCE_GROUP \
          --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}


  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: production

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy PROD container
        run: |
          az containerapp update \
          --name $CONTAINER_APP_PROD \
          --resource-group $RESOURCE_GROUP \
          --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

