name: DevOps CI/CD

on:
  push:
    branches:
      - main

env:
  ACR_NAME: devopsghacr98421
  IMAGE_NAME: devops-node-app
  RESOURCE_GROUP: devops-gha-rg

jobs:

# ---------------------------
# 1. Run Unit Tests
# ---------------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Run Unit Tests
        run: |
          cd app
          npm test


# ---------------------------
# 2. Security Scan (Trivy)
# ---------------------------
  security-scan:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image for scan
        run: |
          docker build -t devops-node-app ./app

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devops-node-app
          format: table
          exit-code: 1
          severity: CRITICAL
          ignore-unfixed: true


# ---------------------------
# 3. Build & Push Image
# ---------------------------
  build-push-image:
    needs: security-scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest ./app

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Push image
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest


# ---------------------------
# 4. Deploy to DEV
# ---------------------------
  deploy-dev:
    needs: build-push-image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy DEV container
        run: |
          az containerapp update \
            --name devops-app-dev \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:latest


# ---------------------------
# 5. Deploy to PROD (Approval)
# ---------------------------
  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy PROD container
        run: |
          az containerapp update \
            --name devops-app-prod \
            --resource-group $RESOURCE_GROUP \
            --image $ACR_NAME.azurecr.io/$IMAGE_NAME:latest